In [ ]:
import pandas as pandas

In [4]:
# 1. 판다스 도구 불러오기 (너무 기니까 pd라는 별명으로 부릅니다)
import pandas as pd

# 2. 데이터 창고(data 폴더)에서 csv 파일을 읽어와서 df라는 변수에 담기
# '../' 는 "현재 폴더(notebooks)에서 한 칸 뒤로 나가라"는 뜻의 아주 중요한 기호입니다.
df = pd.read_csv('../data/electron_charge_practice.csv')

# 3. 데이터가 잘 불러와졌는지 첫 5줄만 미리보기
df.head()

   voltage_v  radius_cm  current_a
0        150          2       2.90
1        150          3       1.09
2        160          2       3.10
3        160          3       1.76
4        160          4       1.17

In [5]:
# 미션: 전류(current)를 입력받으면 자기장(b_field)을 뱉어내는 자판기(함수) 만들기
def calculate_magnetic_field(current):
    # 파이썬에서 10의 거듭제곱은 ** 기호를 씁니다. (예: 10**-4)
    # 또는 공학용 표기법으로 1e-4 라고 적어도 됩니다.
    
    b_field = 6.93 * (10**-4) * current
    
    return b_field

# 만든 함수 테스트해보기: 첫 번째 측정값인 전류 2.90A를 넣어봅니다.
test_b = calculate_magnetic_field(2.90)
print("계산된 자기장:", test_b, "Tesla")

계산된 자기장: 0.0020097 Tesla

In [ ]:
# 미션: 전압(U), 반경(r), 자기장(B)을 넣으면 비전하(e/m)를 계산하는 함수 만들기
def calculate_specific_charge(voltage, radius_cm, b_field):
    # 1. 반경 단위를 cm에서 m로 변환
    radius_m = radius_cm / 100
    
    # 2. 비전하 계산 (빈칸 채우기!)
    e_m = (2 * voltage) / (radius_m**2 * b_field**2)
    
    return e_m

df['b_field_t'] = calculate_magnetic_field(df['current_a'])

df['e_m_ratio'] = calculate_specific_charge(df['voltage_v'], df['radius_cm'], df['b_field_t'])

df.head()

   voltage_v  radius_cm  current_a  b_field_t     e_m_ratio
0        150          2       2.90   0.002010  1.856944e+11
1        150          3       1.09   0.000755  5.841969e+11
2        160          2       3.10   0.002148  1.733405e+11
3        160          3       1.76   0.001220  2.390098e+11
4        160          4       1.17   0.000811  3.042228e+11

In [ ]:
# 파일 위치 정의
import sys
sys.path.append('../src/physlab') 

# 변수이름 정의
import physics_calc as pc

# 테스트
test_result = pc.calculate_magnetic_field(2.90)
print("계산한 결과:", test_result, "Tesla")

계산한 결과: 0.0020097 Tesla

In [12]:
test_result2 = pc.calculate_magnetic_field(3.10)
print("계산한 결과:", test_result2, "Tesla")

계산한 결과: 0.0021483 Tesla